# This GitLab CI/CD configuration file includes three stages:
# 1. build: Compiles the Docker image and pushes it to the GitLab Container Registry.
# 2. test: Runs existing ParaView and VisIt tests.

image: debian:12

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

docker_build:
  # This job builds the Docker image from the Dockerfile and pushes it to the
  # GitLab Container Registry. It only runs on the main/master branch.
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # $CI_REGISTRY_USER, $CI_REGISTRY_PASSWORD, and $CI_REGISTRY are predefined
    # GitLab CI/CD variables that allow Docker to log in to the project's registry.
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # Build the Docker image. $CI_REGISTRY_IMAGE is a predefined variable that
    # resolves to the correct registry path for this project. We explicitly add
    # our desired image name, 'kaust-viz-app'.
    - docker build -t "$CI_REGISTRY_IMAGE/kaust-viz-app:latest" -t "$CI_REGISTRY_IMAGE/kaust-viz-app:$CI_COMMIT_REF_SLUG" .
    # Push both the 'latest' and the branch-specific tag to the registry.
    - docker push "$CI_REGISTRY_IMAGE/kaust-viz-app:latest"
    - docker push "$CI_REGISTRY_IMAGE/kaust-viz-app:$CI_COMMIT_REF_SLUG"
  rules:
    # This ensures the Docker image is only built for commits to the default branches.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

paraview-test-job:   # This job runs in the test stage.
  stage: test
  script:
    - echo "Running ParaView Tests"
    - apt update && apt -y install wget make autoconf gfortran libmpich-dev python3-full python3-pip ffmpeg libsm6 libxext6 libgl1-mesa-glx
    - python3 -V
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip3 install pandas matplotlib psutil scipy
    - wget -O paraview.tar.gz  "https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.13&type=binary&os=Linux&downloadFile=ParaView-5.13.1-osmesa-MPI-Linux-Python3.10-x86_64.tar.gz"
    - mkdir paraview
    - tar xf paraview.tar.gz -C paraview --strip-components 1
    - export PARAVIEW_DIR=$PWD/paraview/bin
    - $PARAVIEW_DIR/pvbatch --version
    - echo "$PWD"
    - ls
    - export PARAVIEW_PATH=$PARAVIEW_DIR
    - REPO_DIR=$PWD
    - cd Testing
    - set +e
    - python3 test_suite.py $REPO_DIR/ --test_type ParaView --paraview_version 5.13.1 --non_gpu_machine || exit $?
    - set -e
    - echo "ParaView tests complete"
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - "ParaView_Vignettes/*/Testing/*.json"
      - "ParaView_Vignettes/*/Testing/*.log"
      - "Testing/*.json"

visit-test-job:
  stage: test
  script:
    - echo "Running VisIt Tests"
    - apt update && apt -y install wget make autoconf gfortran libmpich-dev python3-full python3-pip ffmpeg libsm6 libxext6 curl zip unzip libgl1-mesa-glx
    - python3 -V
    - python3 -m venv test-venv
    - source test-venv/bin/activate
    - pip3 install pandas matplotlib psutil scipy
    - wget -O visit.tar.gz  "https://github.com/visit-dav/visit/releases/download/v3.4.1/visit3_4_1.linux-x86_64-ubuntu22.tar.gz"
    - mkdir visit
    - tar xf visit.tar.gz -C visit --strip-components 1
    - export VISIT_DIR=$PWD/visit/bin
    - $VISIT_DIR/visit -version
    - echo "$PWD"
    - ls
    - export VISIT_PATH=$VISIT_DIR
    - REPO_DIR=$PWD
    - cd Testing
    - set +e
    - python3 test_suite.py $REPO_DIR/ --test_type VisIt --visit_version 3.4.1 --test_number 0 1 2 3 4 5 || exit $?
    - set -e
    - echo "VisIt tests complete"
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - "VisIt_Vignettes/*/Testing/*.json"
      - "VisIt_Vignettes/*/Testing/*.log"
      - "Testing/*.json"

