#!/usr/bin/env python3
#
# Visualization Vignettes
#
# prepare_machine.py
#
# Bring one machine to the point where the vignette suite can run.
#
# WHY THIS EXISTS
#
# Three of the suite's inputs are not in git. Two of them are generated by a
# tool rather than downloaded, and those two do NOT survive being copied
# between machines that run different ParaView versions:
#
#   data/                          fetched once, machine-independent
#   data/topologies/               generated, ParaView major.minor specific
#   ex11_state.pvsm                generated, ParaView major.minor specific
#   ex11_visit.session             generated, VisIt version specific
#   ex11_series.visit              generated, holds absolute paths
#
# Until now that was four commands documented in four places -- a comment in
# each .sbat header, Testing/README.md, data/README.md and the runbook -- and
# nothing checked. Worse, getting it wrong is quiet: an AMR hierarchy written
# by ParaView 6.1.0 opens without complaint under 6.0.1, which then reads 216
# points where 6.1.0 wrote 842. No error. ex09 just reports different numbers
# and fails its numeric gate for a reason that looks like a regression.
#
# So: one idempotent command that does all of it, says what it did and what it
# skipped, and re-does only what is actually stale. The vignettes check the
# same provenance at run time and name this script when it does not match.
#
# USAGE
#
#   python3 Testing/prepare_machine.py                 # both tools, as found
#   python3 Testing/prepare_machine.py --tool ParaView
#   python3 Testing/prepare_machine.py --force         # regenerate regardless
#   python3 Testing/prepare_machine.py --check         # report only, change nothing
#
# It finds pvbatch and visit the same way run_tests.py does: $PARAVIEW_PATH and
# $VISIT_PATH first, then PATH. A tool that is not present is skipped with a
# note, not an error, so this is safe to run on a machine that has only one of
# them.
#
# Author: James Kress, <james@jameskress.com>
#
from __future__ import print_function

import argparse
import json
import os
import re
import shutil
import subprocess
import sys


HERE = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.abspath(os.path.join(HERE, ".."))

DATA_DIR = os.path.join(REPO, "data")
TOPOLOGY_DIR = os.path.join(DATA_DIR, "topologies")
TOPOLOGY_MANIFEST = os.path.join(TOPOLOGY_DIR, "topologies_manifest.json")
TOPOLOGY_GENERATOR = os.path.join(DATA_DIR, "make_topology_datasets.py")

# The XML time series. The shipped legacy series carries no time or cycle at
# all, so ex05 and ex12 read this one instead -- see data/make_time_series.py
# for the measurements that forced it.
TIME_SERIES_DIR = os.path.join(DATA_DIR, "varying_series_xml")
TIME_SERIES_MANIFEST = os.path.join(TIME_SERIES_DIR, "manifest.json")
TIME_SERIES_GENERATOR = os.path.join(DATA_DIR, "make_time_series.py")
TIME_SERIES_SOURCE = os.path.join(DATA_DIR, "varying_data")

PV_STATE_DIR = os.path.join(REPO, "ParaView_Vignettes", "ex11_pvStateVerification")
PV_STATE = os.path.join(PV_STATE_DIR, "ex11_state.pvsm")
PV_STATE_GENERATOR = os.path.join(PV_STATE_DIR, "ex11_make_state.py")

VISIT_STATE_DIR = os.path.join(REPO, "VisIt_Vignettes", "ex11_visitStateVerification")
VISIT_STATE = os.path.join(VISIT_STATE_DIR, "ex11_visit.session")
VISIT_STATE_GENERATOR = os.path.join(VISIT_STATE_DIR, "ex11_make_state.py")
# The generator writes a .visit index beside the session, holding absolute
# paths to this machine's data directory. Neither file is committed and
# neither is portable, so both are checked.
VISIT_SERIES = os.path.join(VISIT_STATE_DIR, "ex11_series.visit")

# Only ex06 needs these, and they are a 4.3 GB download.
LARGE_DATA_MARKERS = (
    os.path.join(DATA_DIR, "cyclone-chapala-2015-11-02_00-00-00-mb.vtm"),
    os.path.join(DATA_DIR, "currentRainfall.silo"),
)


GREEN, YELLOW, RED, RESET = "\033[32m", "\033[33m", "\033[31m", "\033[0m"
if not sys.stdout.isatty():
    GREEN = YELLOW = RED = RESET = ""


def say(symbol, colour, message):
    print("{0}{1}{2} {3}".format(colour, symbol, RESET, message))
    sys.stdout.flush()


def ok(message):
    say("OK  ", GREEN, message)


def todo(message):
    say("MAKE", YELLOW, message)


def bad(message):
    say("FAIL", RED, message)


def skip(message):
    say("SKIP", YELLOW, message)


# ---------------------------------------------------------------------------
# Tool discovery -- same rules as run_tests.py
# ---------------------------------------------------------------------------
def find_executable(name, env_var):
    root = os.getenv(env_var)
    if root:
        candidate = os.path.join(root, name)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return shutil.which(name)


def paraview_version(pvbatch):
    """major.minor.patch of the pvbatch we are about to use, or None.

    Two ways, cheapest first.

    `--version` is a banner every build prints, needs no temp file and no
    import, and is the only one that worked on Shaheen's source build
    (/sw/vis2/.../paraview-buildMesa-6.1.0). That build does not define
    `paraview.__version__`, so the import probe alone returned nothing and
    this reported "unknown" -- while the generators, which fall back to
    GetParaViewVersion(), recorded "6.1.0" into their manifests. The two then
    disagreed and --check called a fixture stale seconds after building it.

    The import probe stays as the fallback, now with the same fallback chain
    the generators use, so the two can no longer reach different answers.
    """
    banner = _run_banner([pvbatch, "--version"])
    if banner:
        return banner

    probe = (
        "import sys, os\n"
        "version = ''\n"
        "try:\n"
        "    import paraview\n"
        "    version = getattr(paraview, '__version__', '') or ''\n"
        "except Exception:\n"
        "    pass\n"
        "if not version:\n"
        "    try:\n"
        "        from paraview.simple import GetParaViewVersion\n"
        "        version = '.'.join(str(p) for p in GetParaViewVersion())\n"
        "    except Exception:\n"
        "        pass\n"
        "sys.stdout.write(version)\n"
        "sys.stdout.flush()\n"
        "os._exit(0)\n"
    )
    return _run_probe(pvbatch, probe, ".py")


def _run_banner(cmd):
    """First version-shaped number from a `--version` style banner, or None.

    stdout and stderr are both read: which one a build uses for its banner is
    not something to depend on.
    """
    try:
        result = subprocess.run(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=60
        )
    except Exception:  # noqa: BLE001 - a probe that fails is just "unknown"
        return None
    text = (result.stdout + result.stderr).decode("utf-8", "replace")
    match = re.search(r"\d+\.\d+(\.\d+)?", text)
    return match.group(0) if match else None


def visit_version(visit):
    probe = (
        "import sys, os\n"
        "sys.stdout.write(str(Version()))\n"
        "sys.stdout.flush()\n"
        "exit(0)\n"
    )
    return _run_probe(visit, probe, ".py", visit=True)


def _run_probe(executable, source, suffix, visit=False):
    import tempfile

    handle, path = tempfile.mkstemp(suffix=suffix)
    try:
        with os.fdopen(handle, "w") as script:
            script.write(source)
        cmd = (
            [executable, "-cli", "-nowin", "-noconfig", "-s", path]
            if visit
            else [executable, path]
        )
        result = subprocess.run(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=180
        )
        text = result.stdout.decode("utf-8", "replace").strip()
        match = re.search(r"\d+\.\d+(\.\d+)?", text)
        return match.group(0) if match else None
    except Exception:  # noqa: BLE001 - a probe that fails is just "unknown"
        return None
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


def major_minor(version):
    if not version:
        return None
    parts = str(version).split(".")
    if len(parts) < 2:
        return None
    try:
        return (int(parts[0]), int(parts[1]))
    except ValueError:
        return None


# ---------------------------------------------------------------------------
# What each fixture says about itself
# ---------------------------------------------------------------------------
def topology_recorded_version():
    if not os.path.exists(TOPOLOGY_MANIFEST):
        return None
    try:
        with open(TOPOLOGY_MANIFEST, "r") as handle:
            return json.load(handle).get("paraview_version")
    except (ValueError, OSError):
        return None


def pvsm_recorded_version(path):
    try:
        with open(path, "r") as handle:
            for _ in range(20):
                line = handle.readline()
                if not line:
                    break
                match = re.search(r'ServerManagerState[^>]*version="([^"]+)"', line)
                if match:
                    return match.group(1)
    except (OSError, IOError):
        pass
    return None


def run(cmd, cwd=None):
    print("    $ {0}".format(" ".join(cmd)))
    sys.stdout.flush()
    result = subprocess.run(cmd, cwd=cwd)
    return result.returncode == 0


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------
def step_large_data(args):
    """ex06's datasets. Machine-independent, so only presence is checked."""
    missing = [p for p in LARGE_DATA_MARKERS if not os.path.exists(p)]
    if not missing:
        ok("ex06 datasets present")
        return True

    todo(
        "ex06 datasets missing ({0})".format(
            ", ".join(os.path.basename(p) for p in missing)
        )
    )
    if args.check:
        return False
    print("    4.3 GB download. Skipping automatically; run it yourself if you")
    print("    intend to run ex06:")
    print("        cd data && ./fetchData.sh")
    return False


def step_topologies(args, pvbatch, pv_version):
    """data/topologies -- generated, and ParaView major.minor specific."""
    recorded = topology_recorded_version()
    present = os.path.exists(TOPOLOGY_MANIFEST)

    if present and not args.force:
        if recorded is None:
            todo("data/topologies exists but records no ParaView version")
        elif major_minor(recorded) == major_minor(pv_version):
            ok("data/topologies generated by ParaView {0}".format(recorded))
            return True
        elif major_minor(pv_version) is None:
            # Not knowing the running version is not evidence of staleness,
            # and treating it as such refused to start a run against fixtures
            # that had just been built by that very pvbatch.
            ok(
                "data/topologies generated by ParaView {0}; cannot read the "
                "running version to compare. Use --force after a module "
                "change.".format(recorded)
            )
            return True
        else:
            todo(
                "data/topologies generated by ParaView {0}, running {1} -- "
                "stale".format(recorded, pv_version)
            )
    elif not present:
        todo("data/topologies missing")
    else:
        todo("data/topologies -- regenerating (--force)")

    if args.check:
        return False
    return run([pvbatch, TOPOLOGY_GENERATOR], cwd=REPO)


def step_time_series(args, pvbatch):
    """data/varying_series_xml -- generated, and only as current as its source.

    Not version-locked: it is plain XML VTK that every build in this
    repository reads identically. It IS source-locked, so a count mismatch
    against data/varying_data means it is stale.
    """
    source_count = 0
    if os.path.isdir(TIME_SERIES_SOURCE):
        source_count = len(
            [n for n in os.listdir(TIME_SERIES_SOURCE) if n.lower().endswith(".vtk")]
        )
    if source_count == 0:
        skip("XML time series: source data/varying_data is absent")
        return True

    recorded = 0
    if os.path.exists(TIME_SERIES_MANIFEST):
        try:
            with open(TIME_SERIES_MANIFEST, "r") as handle:
                recorded = len(json.load(handle).get("timesteps", []))
        except (ValueError, OSError):
            recorded = 0

    if recorded == source_count and not args.force:
        ok("XML time series present ({0} timestep(s))".format(recorded))
        return True

    if recorded == 0:
        todo("XML time series missing")
    elif args.force:
        todo("XML time series -- regenerating (--force)")
    else:
        todo(
            "XML time series has {0} timestep(s), source has {1} -- "
            "stale".format(recorded, source_count)
        )

    if args.check:
        return False
    return run([pvbatch, TIME_SERIES_GENERATOR], cwd=REPO)


def step_pv_state(args, pvbatch, pv_version):
    """ex11_state.pvsm -- generated, and version-locked by design."""
    present = os.path.exists(PV_STATE)
    recorded = pvsm_recorded_version(PV_STATE) if present else None

    if present and not args.force:
        if major_minor(recorded) == major_minor(pv_version):
            ok("ex11_state.pvsm written by ParaView {0}".format(recorded))
            return True
        if recorded and major_minor(pv_version) is None:
            # As in step_topologies: unreadable is not stale.
            ok(
                "ex11_state.pvsm written by ParaView {0}; cannot read the "
                "running version to compare. Use --force after a module "
                "change.".format(recorded)
            )
            return True
        todo(
            "ex11_state.pvsm written by ParaView {0}, running {1} -- "
            "stale".format(recorded or "an unrecorded version", pv_version)
        )
    elif not present:
        todo("ex11_state.pvsm missing")
    else:
        todo("ex11_state.pvsm -- regenerating (--force)")

    if args.check:
        return False
    return run([pvbatch, PV_STATE_GENERATOR], cwd=PV_STATE_DIR)


def step_visit_state(args, visit, visit_ver):
    """ex11_visit.session and ex11_series.visit -- generated, not portable.

    The session is version-locked to the VisIt that wrote it, and the .visit
    index beside it holds absolute paths into this machine's data directory.
    Neither is committed. A .session records no version of its own that can be
    read back cheaply, so presence is what is checked; --force regenerates.
    Regenerate after any VisIt version change, and after moving the checkout
    or the data directory.
    """
    missing = [
        os.path.basename(path)
        for path in (VISIT_STATE, VISIT_SERIES)
        if not os.path.exists(path)
    ]

    if not missing and not args.force:
        ok(
            "ex11_visit.session and ex11_series.visit present (regenerate with "
            "--force after a VisIt version change or a move)"
        )
        return True

    todo(
        "ex11 VisIt fixtures {0}".format(
            "missing: " + ", ".join(missing) if missing else "-- regenerating (--force)"
        )
    )
    if args.check:
        return False

    # --force means "rebuild these", so clear them first. Otherwise the
    # presence check below would pass on the old files if the generator
    # failed, and report a rebuild that never happened.
    if args.force:
        for path in (VISIT_STATE, VISIT_SERIES):
            if os.path.exists(path):
                os.remove(path)

    run(
        [visit, "-cli", "-nowin", "-noconfig", "-s", VISIT_STATE_GENERATOR],
        cwd=VISIT_STATE_DIR,
    )

    # VisIt's launcher exits 250 after a clean shutdown -- see section 4b.1
    # of LOCAL_VALIDATION.md -- so its return code says nothing about whether
    # the generator worked. Taking it at face value here made a successful
    # run report one outstanding item, and `set -e` then killed the whole
    # VisIt CI job before a single vignette ran. The two files it was asked
    # to write are the only honest answer.
    still_missing = [
        os.path.basename(path)
        for path in (VISIT_STATE, VISIT_SERIES)
        if not os.path.exists(path)
    ]
    if still_missing:
        bad("ex11 VisIt fixtures still missing: " + ", ".join(still_missing))
        return False

    ok("ex11_visit.session and ex11_series.visit written")
    return True


# ---------------------------------------------------------------------------
def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate the machine-specific fixtures the vignette "
        "suite needs. Idempotent: only what is missing or stale is rebuilt.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--tool",
        choices=("ParaView", "VisIt", "both"),
        default="both",
        help="Prepare for one tool or both. A tool that is not installed is "
        "skipped either way.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate everything, even what looks current.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report what would be done and change nothing. Exits 0 when "
        "ready, 1 when a generated fixture is missing or stale, and 3 when "
        "only ex06's large download is absent. Usable as a preflight.",
    )
    args = parser.parse_args(argv)

    print("Repository : {0}".format(REPO))
    print("")

    outstanding = 0
    # Absent large data is a DIFFERENT kind of not-ready from a stale
    # fixture. A stale fixture is a correctness trap: it opens, it reads the
    # wrong thing, and the failure arrives later disguised as a regression.
    # A missing 4.3 GB download is just a download somebody has not done,
    # and it should not stop the other twelve vignettes from running or
    # block CI, which has no business fetching it.
    data_missing = 0

    if args.tool in ("ParaView", "both"):
        pvbatch = find_executable("pvbatch", "PARAVIEW_PATH")
        if not pvbatch:
            skip("pvbatch not found (set $PARAVIEW_PATH or load the module)")
        else:
            pv_version = paraview_version(pvbatch) or "unknown"
            print("ParaView   : {0}  ({1})".format(pv_version, pvbatch))
            if not step_topologies(args, pvbatch, pv_version):
                outstanding += 1
            if not step_pv_state(args, pvbatch, pv_version):
                outstanding += 1
            if not step_time_series(args, pvbatch):
                outstanding += 1
        print("")

    if args.tool in ("VisIt", "both"):
        visit = find_executable("visit", "VISIT_PATH")
        if not visit:
            skip("visit not found (set $VISIT_PATH or load the module)")
        else:
            visit_ver = visit_version(visit) or "unknown"
            print("VisIt      : {0}  ({1})".format(visit_ver, visit))
            if not step_visit_state(args, visit, visit_ver):
                outstanding += 1
        print("")

    if not step_large_data(args):
        data_missing = 1

    print("")
    if outstanding == 0 and data_missing == 0:
        ok("this machine is ready")
        return 0

    if outstanding == 0:
        skip("this machine is ready except for ex06's datasets (see above)")
        if not args.check:
            # Generate mode's contract is "build what you can", and it did.
            # The 4.3 GB download is not something it builds; it deliberately
            # refuses to start it. Reporting that as a non-zero exit made
            # `set -e` kill both CI jobs before a single vignette ran, which
            # is a worse outcome than the thing it was warning about.
            return 0
        # --check is a status query, so the code carries the answer: 3 means
        # ready except for ex06. test_suite.py's preflight treats it as a
        # warning, and a caller that genuinely needs ex06 can test for it.
        return 3

    if args.check:
        bad(
            "{0} generated fixture(s) missing or stale -- re-run without "
            "--check".format(outstanding)
        )
        return 1

    bad("{0} item(s) still outstanding (see above)".format(outstanding))
    return 1


if __name__ == "__main__":
    sys.exit(main())
