#
# Visualization Vignettes
#
# vignette_common.py
#
# Shared, stdlib-only support library for every ParaView and VisIt vignette.
#
# This module is imported by scripts running under three different Python
# interpreters -- pvbatch's, VisIt's CLI, and the plain system python3 that
# drives the harness -- so it uses nothing outside the standard library and
# targets Python 3.6+. It must never import paraview or visit modules at
# import time.
#
# WHAT IT PROVIDES
#
#   parse_args()        One CLI contract shared by all vignettes, so the
#                       harness can drive any of them the same way and a
#                       developer can run any of them by hand the same way.
#
#   VignetteContext     Output directories, dataset resolution, logging,
#                       timing, deterministic metrics, and assertions --
#                       written out as a structured results JSON that the
#                       harness compares numerically against a baseline.
#
#   visit_engine_args() Correct compute-engine launch arguments for VisIt,
#                       derived from named CLI flags rather than positional
#                       sys.argv indices.
#
# WHY THE COMPUTE-ENGINE HELPER EXISTS
#
# The original VisIt vignettes selected a machine with `sys.argv[4]`, but the
# Shaheen submission scripts pass five positional arguments, so argv[4] held
# the walltime string and neither branch ever matched. OpenComputeEngine was
# silently skipped and every Shaheen run executed serially on one core while
# reporting success. Named flags remove the whole class of bug.
#
# Author: James Kress, <james@jameskress.com>
#
from __future__ import print_function

import argparse
import errno
import json
import os
import platform
import re
import socket
import sys
import time


SCHEMA_VERSION = 1

# Datasets shipped in the repository, plus the ones produced by
# data/make_topology_datasets.py. Keyed by a short logical name so a vignette
# never hard-codes a relative path.
DATASET_KEYS = {
    "varying_series": "varying_data",
    "varying_first": os.path.join("varying_data", "varying00.vtk"),
    # The XML series, generated by data/make_time_series.py. The legacy
    # series above carries no time or cycle at all; this one does. See
    # time_series_index() for which vignettes read which, and why.
    "time_series_dir": "varying_series_xml",
    "time_series_pvd": os.path.join("varying_series_xml", "series.pvd"),
    "time_series_visit": os.path.join("varying_series_xml", "series.visit"),
    "time_series_manifest": os.path.join("varying_series_xml", "manifest.json"),
    "noise_silo": "noise.silo",
    "topology_dir": "topologies",
    "tetra": os.path.join("topologies", "tetra_unstructured.vtu"),
    "amr": os.path.join("topologies", "amr_hierarchy.vth"),
    "polydata": os.path.join("topologies", "surface_polydata.vtp"),
    "ragged": os.path.join("topologies", "ragged_multiblock.vtm"),
    "ragged_visit": os.path.join("topologies", "ragged_multidomain.visit"),
    "uniform": os.path.join("topologies", "scalar_field.vti"),
    "topology_manifest": os.path.join("topologies", "topologies_manifest.json"),
}

# The scalar carried by the shipped varying*.vtk series, and by every dataset
# that make_topology_datasets.py writes. Vignettes contour on this name.
SHARED_SCALAR = "temp"
TOPOLOGY_SCALAR = "scalar"


class VignetteError(RuntimeError):
    """Raised for any condition that must fail the vignette."""


# ---------------------------------------------------------------------------
# Filesystem helpers
# ---------------------------------------------------------------------------
def _makedirs(path):
    """mkdir -p that is safe on Python 3.6 and against concurrent ranks."""
    try:
        os.makedirs(path)
    except OSError as exc:
        if exc.errno != errno.EEXIST or not os.path.isdir(path):
            raise
    return path


def png_size(path):
    """(width, height) of a PNG, read from its IHDR chunk.

    Implemented against the file format rather than through Pillow, because
    VisIt's bundled Python does not always ship Pillow and a vignette must be
    able to assert its own output resolution without an optional dependency.

    Returns (0, 0) when the file is missing or is not a PNG.
    """
    try:
        with open(path, "rb") as handle:
            header = handle.read(24)
    except (OSError, IOError):
        return (0, 0)

    if len(header) < 24 or header[:8] != b"\x89PNG\r\n\x1a\n":
        return (0, 0)
    if header[12:16] != b"IHDR":
        return (0, 0)

    width = int.from_bytes(header[16:20], "big")
    height = int.from_bytes(header[20:24], "big")
    return (width, height)


def script_directory(script_path=None):
    """Absolute directory holding the running vignette script.

    VisIt's CLI does not always populate __file__ in the way CPython does,
    so callers pass their own __file__ when they have one and this falls
    back to sys.argv[0] when they do not.
    """
    if script_path:
        return os.path.abspath(os.path.dirname(script_path))
    if sys.argv and sys.argv[0]:
        return os.path.abspath(os.path.dirname(sys.argv[0]))
    return os.path.abspath(os.getcwd())


def find_repo_root(start):
    """Walk upward from `start` looking for the repository root.

    Identified by the two vignette suites sitting side by side. Falls back to
    two levels up, which is where a vignette directory sits relative to the
    root, so this still returns something sensible in a partial checkout.
    """
    current = os.path.abspath(start)
    for _ in range(8):
        if os.path.isdir(os.path.join(current, "ParaView_Vignettes")) and os.path.isdir(
            os.path.join(current, "VisIt_Vignettes")
        ):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    return os.path.abspath(os.path.join(start, "..", ".."))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser(name, tool, description=None):
    """The CLI contract every vignette shares.

    Kept deliberately small: anything a vignette needs beyond this is added
    by the caller through the returned parser before parse_args() runs.
    """
    parser = argparse.ArgumentParser(
        prog=name,
        description=description or "{0} vignette: {1}".format(tool, name),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    io_group = parser.add_argument_group("input and output")
    io_group.add_argument(
        "--data-dir",
        default=None,
        help="Directory holding the static datasets. Defaults to $VV_DATA_DIR, "
        "then <repo>/data.",
    )
    io_group.add_argument(
        "--output-dir",
        default=None,
        help="Where rendered images and extracts are written. "
        "Defaults to <script-dir>/output.",
    )
    io_group.add_argument(
        "--testing-dir",
        default=None,
        help="Where the structured results JSON is written. "
        "Defaults to <script-dir>/Testing.",
    )

    run_group = parser.add_argument_group("execution")
    run_group.add_argument(
        "--machine",
        choices=("local", "ibex", "shaheen"),
        default="local",
        help="Execution site. Selects the VisIt compute-engine launch profile; "
        "'local' runs in-process and never launches an engine.",
    )
    run_group.add_argument(
        "--ranks", type=int, default=1, help="MPI ranks the vignette should use."
    )
    run_group.add_argument(
        "--nodes", type=int, default=1, help="Compute nodes the vignette should use."
    )
    run_group.add_argument(
        "--partition", default="batch", help="Scheduler partition or queue name."
    )
    run_group.add_argument(
        "--account", default=None, help="Scheduler account to charge, when required."
    )
    run_group.add_argument(
        "--walltime", default="00:20:00", help="Walltime for a launched compute engine."
    )

    img_group = parser.add_argument_group("rendering")
    img_group.add_argument(
        "--image-width", type=int, default=1024, help="Rendered image width in pixels."
    )
    img_group.add_argument(
        "--image-height",
        type=int,
        default=1024,
        help="Rendered image height in pixels.",
    )
    img_group.add_argument(
        "--timesteps",
        type=int,
        default=0,
        help="Number of timesteps to process. 0 means every timestep available.",
    )

    parser.add_argument(
        "--verbose", action="store_true", help="Emit per-step progress logging."
    )
    parser.add_argument(
        "--no-metrics",
        "--ephemeral",
        dest="write_metrics",
        action="store_false",
        default=(
            os.environ.get("VV_NO_METRICS", "") not in ("1", "true", "TRUE", "yes")
        ),
        help="Mark this as a throwaway run. A vignette writes no permanent "
        "history of its own -- its results JSON is a comparison input, not a "
        "history -- so this only records the intent in the log. The harness "
        "flag of the same name is what keeps the run out of "
        "performance_metrics_<machine>.json. Defaults from $VV_NO_METRICS.",
    )
    return parser


def parse_args(name, tool, description=None, extend=None, argv=None):
    """Parse the shared CLI, tolerating host-injected arguments.

    pvbatch and VisIt both forward their own flags into sys.argv, so unknown
    arguments are collected rather than treated as an error. They are logged
    once by VignetteContext so a genuine typo is still visible.
    """
    parser = build_parser(name, tool, description)
    if extend is not None:
        extend(parser)
    args, unknown = parser.parse_known_args(argv)
    args.unknown_args = unknown
    return args


# ---------------------------------------------------------------------------
# Timing
# ---------------------------------------------------------------------------
class _Phase(object):
    """Context manager returned by VignetteContext.phase()."""

    def __init__(self, ctx, label, accumulate=False):
        self._ctx = ctx
        self._label = label
        self._accumulate = accumulate
        self._start = 0.0

    def __enter__(self):
        self._start = time.time()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        elapsed = time.time() - self._start
        self._ctx.add_timing(self._label, elapsed, accumulate=self._accumulate)
        if exc_type is None:
            self._ctx.debug("{0}: {1:.4f} s".format(self._label, elapsed))
        return False


# ---------------------------------------------------------------------------
# Context
# ---------------------------------------------------------------------------
class VignetteContext(object):
    """Everything a vignette needs that is not ParaView or VisIt itself.

    Metrics and timings are kept apart on purpose. `metrics` holds
    deterministic quantities -- point counts, cell counts, scalar ranges --
    which the harness compares numerically against a baseline with a
    tolerance. `timings` holds wall-clock durations, which are recorded for
    the scaling CSV and never regression-compared, because comparing a wall
    time against a stored baseline produces a test that fails whenever the
    machine is busy.
    """

    def __init__(self, name, tool, args, script_path=None, script_dir=None):
        self.name = name
        self.tool = tool
        self.args = args

        # `script_dir` is the directory itself; `script_path` is a file within
        # it. Vignettes normally pass script_dir, because VisIt's CLI does not
        # reliably populate __file__ and the bootstrap has already resolved
        # the directory by the time the context is built.
        if script_dir:
            self.script_dir = os.path.abspath(script_dir)
        else:
            self.script_dir = script_directory(script_path)
        self.repo_root = find_repo_root(self.script_dir)

        self.data_dir = os.path.abspath(
            args.data_dir
            or os.environ.get("VV_DATA_DIR")
            or os.path.join(self.repo_root, "data")
        )
        self.output_dir = _makedirs(
            os.path.abspath(args.output_dir or os.path.join(self.script_dir, "output"))
        )
        self.testing_dir = _makedirs(
            os.path.abspath(
                args.testing_dir or os.path.join(self.script_dir, "Testing")
            )
        )

        # Whether this run is meant to be recorded. Nothing in a vignette
        # appends to the committed performance history, so this changes no
        # behaviour here; it is carried and logged so the whole chain --
        # test_suite.py, run_tests.py, the vignette -- agrees about what kind
        # of run this is when somebody reads the log afterwards.
        self.write_metrics = getattr(args, "write_metrics", True)

        self.metrics = {}
        self.timings = {}
        self.assertions = []
        self.images = []
        self.extracts = []
        # CSVs the vignette wants regression-compared numerically rather than
        # eyeballed. Declared explicitly, and deliberately NOT inferred from
        # self.extracts: write_timing_csv() also lands there, and a wall-clock
        # file compared against a baseline is a test that fails whenever the
        # machine is busy.
        self.numeric_extracts = []
        # An image tolerance this vignette asks for instead of the suite
        # default. None means "use whatever --image-tolerance says".
        self.image_tolerance = None
        self.notes = []
        self._start = time.time()

        self.log("=" * 68)
        self.log("{0} vignette: {1}".format(tool, name))
        self.log("=" * 68)
        self.log("script dir : {0}".format(self.script_dir))
        self.log("repo root  : {0}".format(self.repo_root))
        self.log("data dir   : {0}".format(self.data_dir))
        self.log("output dir : {0}".format(self.output_dir))
        self.log("testing dir: {0}".format(self.testing_dir))
        self.log(
            "machine    : {0}  nodes={1} ranks={2}".format(
                args.machine, args.nodes, args.ranks
            )
        )
        self.log(
            "host       : {0} ({1})".format(socket.gethostname(), platform.system())
        )
        if not self.write_metrics:
            self.log("history    : suppressed (--no-metrics)")
        if getattr(args, "unknown_args", None):
            self.log(
                "passthrough args ignored: {0}".format(" ".join(args.unknown_args))
            )
        self.log("-" * 68)

    # -- logging ---------------------------------------------------------
    def log(self, message):
        print("[{0}] {1}".format(self.name, message))
        sys.stdout.flush()

    def debug(self, message):
        if self.args.verbose:
            self.log(message)

    def warn(self, message):
        print("[{0}] WARNING: {1}".format(self.name, message))
        sys.stdout.flush()
        self.notes.append(message)

    def error(self, message):
        """Report a problem loudly without deciding the exit code here.

        The verdict belongs to an assertion -- assert_true or assert_close --
        so that it lands in the results JSON and is compared like any other.
        This only makes sure the reason is legible in the log next to the
        failure, and is kept in the notes for whoever reads the JSON instead.
        """
        print("[{0}] ERROR: {1}".format(self.name, message))
        sys.stdout.flush()
        self.notes.append("ERROR: " + message)

    # -- datasets --------------------------------------------------------
    def dataset(self, key_or_relpath, required=True):
        """Resolve a dataset path and confirm it exists.

        Accepts either a logical key from DATASET_KEYS or a path relative to
        the data directory. A missing dataset raises with the command that
        produces it, rather than failing later inside a reader with a message
        about a null pointer.
        """
        relative = DATASET_KEYS.get(key_or_relpath, key_or_relpath)
        path = os.path.join(self.data_dir, relative)
        if os.path.exists(path):
            return path
        if not required:
            return None

        hint = "Run data/fetchData.sh to download the shipped datasets."
        if "topologies" in relative:
            hint = (
                "Run:  pvbatch data/make_topology_datasets.py --output-dir "
                "{0}".format(os.path.join(self.data_dir, "topologies"))
            )
        raise VignetteError("Required dataset not found: {0}\n  {1}".format(path, hint))

    def time_series_index(self):
        """Path to the index file for the XML time series, for THIS tool.

        WHY THERE IS A SECOND SERIES

        data/varying_data/varying*.vtk carries no time and no cycle. Nothing
        in those files says which timestep they are, so both ParaView and
        VisIt synthesize a time from the file's position in the series --
        and VisIt 3.4.2 changed what it synthesizes, from the state index to
        zero. Measured over the same twenty files:

            legacy .vtk    ParaView 0,1,2..   3.4.1 0,1,2..   3.4.2 0,0,0..

        No vignette fix reaches that, because no vignette was reading a time.
        data/make_time_series.py converts the series to XML .vtr with a .pvd
        for ParaView and a .visit for VisIt, and both then report the same
        real times and cycles on every build tested.

        ex05 and ex12, whose subject IS time, read this. ex07, ex10 and ex11
        keep the legacy series, so ex11 goes on exercising ParaView's
        LegacyVTKReader through a saved state, which is what that vignette is
        for. Having both is the point: one series shows what a reader does
        when the data tells it the time, the other shows what it does when
        the data does not.
        """
        key = "time_series_visit" if self.tool == "VisIt" else "time_series_pvd"
        try:
            return self.dataset(key)
        except VignetteError:
            raise VignetteError(
                "The XML time series has not been generated on this machine.\n"
                "  Run:  python3 Testing/prepare_machine.py\n"
                "  or:   pvbatch data/make_time_series.py"
            )

    def time_series_table(self):
        """The generator's own record of (timestep, cycle, time) per state.

        Used as the fallback when a reader will not report a value, and as
        the thing a reader's answer is checked against. Returns [] when the
        manifest is missing rather than raising, so a caller can degrade.
        """
        path = self.dataset("time_series_manifest", required=False)
        if not path:
            return []
        try:
            with open(path, "r") as handle:
                return json.load(handle).get("timesteps", [])
        except (OSError, IOError, ValueError):
            return []

    def timestep_files(self, limit=None):
        """Sorted absolute paths of the varying*.vtk time series.

        Built by listing the directory rather than by reading varying.visit,
        whose entries are relative to a working directory the harness does not
        guarantee.
        """
        series_dir = self.dataset("varying_series")
        names = sorted(f for f in os.listdir(series_dir) if f.lower().endswith(".vtk"))
        if not names:
            raise VignetteError("No .vtk timesteps found in {0}".format(series_dir))
        paths = [os.path.join(series_dir, f) for f in names]

        if limit is None:
            limit = getattr(self.args, "timesteps", 0)
        if limit and limit > 0:
            paths = paths[:limit]
        return paths

    def topology_manifest(self):
        """Load the manifest written by data/make_topology_datasets.py.

        The manifest, not the vignette, is the authority on which scalar each
        topology carries and at what value it should be contoured. That keeps
        the vignettes correct even when a source refuses to rename its array
        -- the AMR pulse being the case that actually happens.
        """
        path = self.dataset("topology_manifest")
        with open(path, "r") as handle:
            manifest = json.load(handle)
        self.debug("loaded topology manifest: {0}".format(path))
        return manifest

    # -- output paths ----------------------------------------------------
    def image_path(self, filename):
        path = os.path.join(self.output_dir, filename)
        if filename not in self.images:
            self.images.append(filename)
        return path

    def extract_path(self, filename):
        path = os.path.join(self.output_dir, filename)
        if filename not in self.extracts:
            self.extracts.append(filename)
        return path

    def baseline_ranks(self):
        """The rank count the committed baseline images were blessed at.

        Read from the baseline's own results JSON, which records `ranks`
        alongside everything else. Returns None when there is no baseline yet,
        or when it predates that field.
        """
        path = os.path.join(self.testing_dir, "Baseline", self.results_filename())
        try:
            with open(path, "r") as handle:
                return json.load(handle).get("ranks")
        except (OSError, IOError, ValueError):
            return None

    def disable_image_gate_off_baseline_ranks(self, what):
        """Turn the image gate off when this run's rank count is not the one
        the baseline was blessed at, and say so.

        WHY THIS EXISTS

        Translucent geometry is composited in an order that depends on how the
        data is partitioned, so a scene built from overlapping semi-transparent
        plots does not render the same at one rank as at eight. Measured on
        ex06_visitLargeData, VisIt 3.4.1, same data, same script:

            8 ranks vs 8 ranks (the 2025 baseline)   mean |diff| 2.4,  0.6% over 16 levels
            1 rank  vs 8 ranks                       mean |diff| 13.8, 23%  over 16 levels

        Opaque scenes are not affected at all: twelve images across ex01, ex09,
        ex10 and ex12 came back bit-identical at eight ranks.

        So the image is reproducible -- at its own rank count. Comparing across
        rank counts is comparing two different, equally correct renders, and no
        tolerance that still catches a real regression can absorb 23%. This
        turns the gate off for that case only, loudly, and leaves it sharp
        where it means something. Every other gate -- assertions, metrics,
        extracts -- stays live.
        """
        blessed = self.baseline_ranks()
        running = int(getattr(self.args, "ranks", 1) or 1)
        if blessed is None or int(blessed) == running:
            return False

        self.warn(
            "image gate disabled: the baseline was blessed at {0} rank(s) and "
            "this run is at {1}. {2} is composited in a partition-dependent "
            "order, so the two renders differ by roughly 23% of pixels while "
            "both are correct. Bless at {0} rank(s), or compare the numbers "
            "rather than the picture.".format(blessed, running, what)
        )
        self.notes.append(
            "image_gate=disabled (baseline_ranks={0}, run_ranks={1})".format(
                blessed, running
            )
        )
        self.set_image_tolerance(
            1.0,
            "rank count differs from the baseline's; see the warning above",
        )
        return True

    def set_image_tolerance(self, fraction, reason=""):
        """Ask the harness for a different image tolerance for this vignette.

        The suite default (0.001, one pixel in a thousand) is tight enough to
        catch a geometry or colour-map change and loose enough to absorb
        driver dithering. A vignette whose rendering is legitimately noisier
        says so here rather than having the whole suite loosened around it --
        raising --image-tolerance globally to accommodate one vignette blinds
        every other one, and the differences being absorbed are not the same
        size: the widest legitimate cross-backend difference measured in this
        suite is 0.39% (ex09 tetra, NVIDIA GLX vs Mesa llvmpipe), while ex06
        moves 4% against its own output on the same machine.

        `reason` is recorded next to the number, because a loosened gate
        without a stated reason is indistinguishable from a forgotten one.
        """
        self.image_tolerance = float(fraction)
        self.log(
            "image tolerance for this vignette: {0:.4%}{1}".format(
                self.image_tolerance, "  ({0})".format(reason) if reason else ""
            )
        )
        if reason:
            self.notes.append(
                "image tolerance {0:.4%}: {1}".format(self.image_tolerance, reason)
            )
        return self.image_tolerance

    def add_numeric_extract(
        self,
        filename,
        key_columns=None,
        ignore_columns=None,
        rtol=None,
        atol=None,
    ):
        """Declare a CSV in output/ as a numeric regression artifact.

        The harness compares every declared file against the copy in
        Testing/Baseline/ with verify.compare_csv, cell by cell and with a
        tolerance -- not by diffing pixels, and not by requiring bit-identical
        floats. --bless copies the declared files into the baseline directory.

        `key_columns` names the columns that identify a row, so rows are
        matched by identity rather than by position; that matters the moment a
        vignette emits its rows in a different order. `ignore_columns` skips
        columns that legitimately move between runs -- a hostname, a wall
        time -- which is what makes it safe to put timings in the same file as
        the measurements. `rtol`/`atol` override the harness defaults for this
        file, because the right tolerance is a property of the quantity, and
        only the vignette knows what it computed.
        """
        record = {"file": filename}
        if key_columns:
            record["key_columns"] = list(key_columns)
        if ignore_columns:
            record["ignore_columns"] = list(ignore_columns)
        if rtol is not None:
            record["rtol"] = float(rtol)
        if atol is not None:
            record["atol"] = float(atol)

        for existing in self.numeric_extracts:
            if existing.get("file") == filename:
                existing.update(record)
                break
        else:
            self.numeric_extracts.append(record)

        if filename not in self.extracts:
            self.extracts.append(filename)
        self.log("numeric extract declared: {0}".format(filename))
        return os.path.join(self.output_dir, filename)

    # -- results ---------------------------------------------------------
    def phase(self, label, accumulate=False):
        """`with ctx.phase("render"):` records a wall time under that label.

        Pass accumulate=True inside a loop -- over timesteps, say -- to sum
        every iteration into one total rather than keeping only the last.
        """
        return _Phase(self, label, accumulate=accumulate)

    def add_timing(self, label, seconds, accumulate=False):
        value = float(seconds)
        if accumulate:
            value += float(self.timings.get(label, 0.0))
        self.timings[label] = round(value, 6)

    def add_metric(self, key, value):
        """Record a deterministic quantity for numeric baseline comparison."""
        if isinstance(value, bool):
            self.metrics[key] = value
        elif isinstance(value, (int, float)):
            self.metrics[key] = value
        elif isinstance(value, (list, tuple)):
            self.metrics[key] = [
                v if isinstance(v, (int, float, bool)) else str(v) for v in value
            ]
        else:
            self.metrics[key] = str(value)
        self.debug("metric {0} = {1}".format(key, self.metrics[key]))

    def assert_true(self, name, condition, detail=""):
        """Record an assertion. Returns the condition so callers can branch."""
        passed = bool(condition)
        self.assertions.append({"name": name, "passed": passed, "detail": str(detail)})
        self.log(
            "  [{0}] {1}{2}".format(
                "PASS" if passed else "FAIL", name, "  " + str(detail) if detail else ""
            )
        )
        return passed

    def assert_close(self, name, actual, expected, tolerance, detail=""):
        """Assert a float lands within an absolute tolerance."""
        try:
            ok = abs(float(actual) - float(expected)) <= float(tolerance)
        except (TypeError, ValueError):
            ok = False
        note = "actual={0} expected={1} tol={2}".format(actual, expected, tolerance)
        return self.assert_true(name, ok, (detail + " " + note).strip())

    @property
    def failed_assertions(self):
        return [a for a in self.assertions if not a["passed"]]

    # -- serialization ---------------------------------------------------
    def results_filename(self):
        return "{0}_results.json".format(self.name)

    def write_results(self, status="ok", message=""):
        """Write the structured results JSON the harness compares against.

        Written to the Testing/ directory alongside the legacy output.log so
        it sits next to the existing text and image artifacts rather than
        replacing them.
        """
        payload = {
            "schema_version": SCHEMA_VERSION,
            "vignette": self.name,
            "tool": self.tool,
            "status": status,
            "message": message,
            "hostname": socket.gethostname(),
            "platform": platform.system(),
            "machine": self.args.machine,
            "nodes": self.args.nodes,
            "ranks": self.args.ranks,
            "image_size": [self.args.image_width, self.args.image_height],
            "wall_time_s": round(time.time() - self._start, 6),
            "metrics": self.metrics,
            "timings": self.timings,
            "assertions": self.assertions,
            "images": self.images,
            "extracts": self.extracts,
            "numeric_extracts": self.numeric_extracts,
            "image_tolerance": self.image_tolerance,
            "notes": self.notes,
        }
        path = os.path.join(self.testing_dir, self.results_filename())
        with open(path, "w") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        self.log("wrote results: {0}".format(path))
        return path

    def skip(self, reason, exit_func=None):
        """Declare this vignette not runnable here, and stop.

        This is for an input that is absent by design rather than by mistake.
        `data/fetchData.sh` pulls 5.7 GB that deliberately does not live in
        the repository, so a clone that has not run it, and CI, which has no
        business downloading it, are both expected states. A vignette that
        cannot find that input has not failed and must not be reported as a
        regression: it writes `status: "skipped"` with a reason, and the
        harness records a skip, runs no comparisons, and appends no metrics.

        A missing input that is NOT in that category is still a failure. Use
        `ctx.dataset(key)`, which raises, for anything the repository ships
        or generates.
        """
        self.log("SKIPPED: {0}".format(reason))
        self.notes.append("SKIPPED: " + reason)
        self.write_results(status="skipped", message=reason)
        (exit_func or exit_vignette)(0)

    def write_timing_csv(self, filename=None, rows=None):
        """Write a scaling/timing CSV next to the images.

        `rows` is a list of dicts; when omitted the recorded timings are
        written as a single row. Kept as plain csv text so the file is
        readable without pandas on a login node.
        """
        filename = filename or "{0}_timings.csv".format(self.name)
        path = os.path.join(self.output_dir, filename)

        if rows is None:
            row = {
                "vignette": self.name,
                "tool": self.tool,
                "machine": self.args.machine,
                "nodes": self.args.nodes,
                "ranks": self.args.ranks,
                "hostname": socket.gethostname(),
            }
            row.update(self.timings)
            rows = [row]

        if not rows:
            return None

        columns = []
        for row in rows:
            for key in row:
                if key not in columns:
                    columns.append(key)

        with open(path, "w") as handle:
            handle.write(",".join(columns) + "\n")
            for row in rows:
                handle.write(
                    ",".join(_csv_cell(row.get(col, "")) for col in columns) + "\n"
                )
        self.log("wrote timings: {0}".format(path))
        if filename not in self.extracts:
            self.extracts.append(filename)
        return path

    def assert_baselined_images_present(self, baseline_dir=None):
        """Assert every baselined image was produced by this run.

        Driven from the blessed baseline rather than from whatever the run
        happened to emit, so a vignette that quietly stops writing one of its
        frames fails here instead of passing with fewer images than before.

        A vignette with no image baselines yet -- ex00, or one not yet
        blessed -- records the fact and asserts nothing, which keeps this
        safe to add to existing vignettes.
        """
        baseline_dir = baseline_dir or os.path.join(self.testing_dir, "Baseline")
        if not os.path.isdir(baseline_dir):
            self.log(
                "no baseline directory at {0}; image check skipped".format(baseline_dir)
            )
            return True

        suffixes = (".png", ".jpg", ".jpeg")
        baselined = sorted(
            name for name in os.listdir(baseline_dir) if name.lower().endswith(suffixes)
        )
        if not baselined:
            self.log("no baselined images; image presence check skipped")
            self.add_metric("baselined_images", 0)
            return True

        missing = [
            name
            for name in baselined
            if not os.path.exists(os.path.join(self.output_dir, name))
        ]

        self.add_metric("baselined_images", len(baselined))
        self.add_metric("missing_images", len(missing))

        for name in baselined:
            if name not in self.images:
                self.images.append(name)

        return self.assert_true(
            "every baselined image was produced",
            not missing,
            "missing from {0}: {1}".format(self.output_dir, missing)
            if missing
            else "{0} image(s) present".format(len(baselined)),
        )

    def finish(self):
        """Write results and return the process exit code.

        Any failed assertion makes the whole vignette fail. The harness relies
        on this return value, so a vignette must always end with
        `sys.exit(ctx.finish())` rather than falling off the end.
        """
        failures = self.failed_assertions
        status = "ok" if not failures else "failed"
        message = (
            "" if not failures else "{0} assertion(s) failed".format(len(failures))
        )
        self.write_results(status=status, message=message)

        self.log("-" * 68)
        if failures:
            self.log("RESULT: FAILED ({0} assertion(s))".format(len(failures)))
            for item in failures:
                self.log("  - {0}: {1}".format(item["name"], item["detail"]))
        else:
            self.log(
                "RESULT: PASSED ({0} assertion(s), {1} image(s))".format(
                    len(self.assertions), len(self.images)
                )
            )
        self.log("=" * 68)
        return 1 if failures else 0

    def abort(self, exc):
        """Record a fatal error, write results, and return the exit code."""
        message = "{0}: {1}".format(type(exc).__name__, exc)
        print("[{0}] FATAL: {1}".format(self.name, message), file=sys.stderr)
        sys.stderr.flush()
        self.assertions.append(
            {"name": "vignette completed", "passed": False, "detail": message}
        )
        try:
            self.write_results(status="error", message=message)
        except Exception as write_error:  # pragma: no cover - last-resort path
            print(
                "[{0}] could not write results: {1}".format(self.name, write_error),
                file=sys.stderr,
            )
        return 2


_PRINTF_SPEC_RE = re.compile(r"^%([-+ #0]*)(\d*)(?:\.(\d+))?([a-zA-Z])$")


def _printf_to_format_spec(spec):
    """Translate a printf conversion into a std::format one, or None.

    "%-#6.3g" -> "{:<#6.3g}". Only the flag/width/precision/conversion shape
    ParaView's number formats actually use is handled; anything else returns
    None so the caller keeps the original rather than guessing.
    """
    match = _PRINTF_SPEC_RE.match((spec or "").strip())
    if not match:
        return None
    flags, width, precision, conversion = match.groups()
    align = "<" if "-" in flags else ""
    remaining = "".join(flag for flag in flags if flag != "-")
    out = "{:" + align + remaining + (width or "")
    if precision:
        out += "." + precision
    return out + conversion + "}"


def number_format(proxy, printf_spec, property_name="LabelFormat"):
    """Return `printf_spec` in the number-format dialect this build speaks.

    ParaView 5.x formats scalar-bar numbers with printf conversions
    ("%-#6.3g"). ParaView 6.x formats them with std::format specs
    ("{:<#6.3g}") -- and it does not reject a printf string, it prints it
    verbatim. ex06's QICE legend is the visible case: under 5.13 its ticks
    read 0.000 / 0.001, under 6.1 every tick reads "%-#6.3f". Nothing in the
    suite asserts on legend text, so blessing a 6.1 baseline would have
    recorded that as correct.

    Which dialect the build speaks is read from the build's own default for
    `property_name` -- so this needs no version test and no table to keep up
    to date. Call it on a freshly fetched scalar bar, before assigning to the
    property, so the value read is still the default.
    """
    try:
        current = str(proxy.GetPropertyValue(property_name) or "")
    except Exception:  # noqa: BLE001 - an unreadable property means "assume 5.x"
        current = ""

    if not current.strip().startswith("{"):
        return printf_spec

    converted = _printf_to_format_spec(printf_spec)
    return converted if converted else printf_spec


# Every property a preset can land in. A continuous preset writes RGBPoints;
# a categorical one writes IndexedColors and leaves RGBPoints untouched, so
# reading only the first made ex10's "VV Categorical" look like a preset that
# had not been applied.
_TRANSFER_FUNCTION_PROPERTIES = ("RGBPoints", "Points", "IndexedColors", "NanColor")


def _transfer_function_signature(lut):
    """A comparable snapshot of a colour transfer function, or None.

    Used to tell an applied preset from one that was accepted and ignored.
    Returns None when nothing readable is found, in which case the caller
    falls back to trusting ApplyPreset -- which is what every release before
    6.0.1 allowed.
    """
    signature = []
    for prop in _TRANSFER_FUNCTION_PROPERTIES:
        try:
            value = lut.GetPropertyValue(prop)
        except Exception:  # noqa: BLE001 - property absent on this proxy
            continue
        if value:
            signature.append((prop, tuple(value)))
    return tuple(signature) if signature else None


# Presets used only to move the transfer function off whatever it currently
# holds, so that "unchanged" becomes meaningful. Any preset every ParaView
# ships will do; these are tried in order and the first one that actually
# changes something wins.
_SENTINEL_PRESETS = ("Grayscale", "Cool to Warm", "Jet", "Rainbow Desaturated")


def _force_distinct_state(lut, avoid):
    """Move `lut` off its current state, and return the new signature.

    Returns None when no sentinel could be applied, in which case the caller
    has no way to disambiguate and falls back to trusting ApplyPreset.
    """
    start = _transfer_function_signature(lut)
    if start is None:
        return None

    for sentinel in _SENTINEL_PRESETS:
        if sentinel in avoid:
            continue
        try:
            lut.ApplyPreset(sentinel, True)
        except Exception:  # noqa: BLE001 - this build does not have it
            continue
        signature = _transfer_function_signature(lut)
        if signature is not None and signature != start:
            return signature
    return None


def _preset_resolves(lut, name, avoid):
    """Disambiguate "nothing changed" by re-applying from a known state.

    Reached only when applying `name` left the transfer function untouched,
    which has two very different causes: the preset was ALREADY active (the
    normal case -- ex09 colours four topologies through one lookup table), or
    the name does not resolve and this ParaView silently ignored it (6.0.1).

    Moving to a sentinel state first tells them apart, and the preset is
    re-applied either way, so the lookup table ends up in the state the
    caller asked for whenever the answer is yes.
    """
    sentinel_signature = _force_distinct_state(lut, avoid)
    if sentinel_signature is None:
        return None  # cannot tell; caller decides

    try:
        lut.ApplyPreset(name, True)
    except Exception:  # noqa: BLE001
        return False
    return _transfer_function_signature(lut) != sentinel_signature


def apply_color_preset(lut, candidates, ctx=None):
    """Apply the first colour preset this ParaView build actually has.

    ParaView renamed the matplotlib colour maps, and not where you would
    expect -- the rename landed in 6.1, not 6.0, so all three ParaViews this
    repository targets disagree with each other::

        ParaView 5.13.1  "Viridis (matplotlib)"
        ParaView 6.0.1   "Viridis (matplotlib)"   <- Ibex
        ParaView 6.1.0   "Viridis"                <- Shaheen, and local

    All three also fail differently for a name they do not have, which is why
    neither the exception nor the return value is enough on its own:

      * 6.1 raises RuntimeError("no preset with name `%s` present").
      * 5.13 returns False and logs a warning.
      * 6.0.1 does NEITHER. It returns something truthy and silently leaves
        the transfer function exactly as it was. Measured: ex09's tetra
        contour renders teal on 6.1.0 and pale yellow on 6.0.1 -- 26.5% of
        the frame -- because "Viridis" resolved on one and quietly did
        nothing on the other, leaving the default Cool to Warm in place, with
        every assertion in the vignette still passing.

    So the transfer function itself is the witness. A preset that changed
    nothing is only investigated further, never assumed wrong: re-applying it
    from a deliberately different starting state separates "already active"
    from "not there". That extra step runs only in the ambiguous case, so the
    normal path leaves the lookup table untouched -- which matters for a
    categorical map, whose annotations should not be disturbed to prove a
    point.

    `candidates` is every spelling the preset has had, most current first.
    Returns the name applied; raises VignetteError when none work, because
    rendering in the wrong colours is worse than not rendering at all.
    """
    if isinstance(candidates, str):
        candidates = (candidates,)
    candidates = tuple(candidates)

    tried = []
    for name in candidates:
        before = _transfer_function_signature(lut)
        try:
            applied = lut.ApplyPreset(name, True)
        except Exception as exc:  # noqa: BLE001 - 6.1 raises here
            tried.append("{0}: {1}".format(name, exc))
            continue

        # 5.13 returns a bool; 6.x returns None on success. Only an explicit
        # False means "this build does not have that preset".
        if applied is False:
            tried.append("{0}: not present in this ParaView".format(name))
            continue

        after = _transfer_function_signature(lut)
        if before is None or after != before:
            if ctx is not None:
                ctx.debug("applied colour preset: {0}".format(name))
            return name

        resolves = _preset_resolves(lut, name, candidates)
        if resolves is None or resolves:
            if ctx is not None:
                ctx.debug("colour preset already active: {0}".format(name))
            return name

        tried.append(
            "{0}: accepted but the transfer function did not change, and did "
            "not change from a sentinel state either".format(name)
        )

    raise VignetteError("No usable colour preset. Tried: {0}".format("; ".join(tried)))


def major_minor(version):
    """('6', '1') from "6.1.0", or None when it cannot be parsed."""
    if not version:
        return None
    parts = str(version).strip().split(".")
    if len(parts) < 2:
        return None
    try:
        return (int(parts[0]), int(parts[1]))
    except ValueError:
        return None


def check_fixture_version(ctx, recorded, running, what, regenerate):
    """Fail loudly when a generated fixture came from a different toolchain.

    The fixtures under data/topologies/ and the .pvsm state file are produced
    by a tool, not downloaded, and they are NOT portable across a ParaView
    major.minor boundary. What makes that worth a check rather than a note is
    that the failure is silent: an AMR hierarchy written by 6.1.0 opens
    without complaint under 6.0.1, which reads 216 points where 6.1.0 wrote
    842. No exception, no warning -- just different numbers, surfacing much
    later as a numeric-gate mismatch that looks like a regression in the
    vignette rather than a stale fixture.

    So the fixture is asked where it came from, and a mismatch names the one
    command that fixes it. A fixture with no recorded version is warned about
    rather than failed, so an older checkout still runs.
    """
    recorded_mm = major_minor(recorded)
    running_mm = major_minor(running)

    if recorded_mm is None:
        ctx.warn(
            "{0} records no generating version. It cannot be checked against "
            "the running {1}. Regenerate it to remove the doubt:\n    "
            "{2}".format(what, running, regenerate)
        )
        return True

    if running_mm is None or recorded_mm == running_mm:
        ctx.debug(
            "{0} was generated by {1}, running {2}".format(what, recorded, running)
        )
        return True

    raise VignetteError(
        "{0} was generated by ParaView {1}, but this is ParaView {2}. These "
        "fixtures are not portable across a major.minor boundary and the "
        "mismatch does not announce itself -- it shows up as wrong point and "
        "cell counts. Regenerate on this machine:\n    {3}".format(
            what, recorded, running, regenerate
        )
    )


def paraview_version_string():
    """The running ParaView's version string, or "unknown".

    Kept here so the vignettes and the fixture generator agree on what they
    are comparing. Imports paraview lazily: this module is also imported by
    VisIt's CLI and by the plain system python that drives the harness.
    """
    try:
        import paraview

        version = getattr(paraview, "__version__", None)
        if version:
            return str(version)
        from paraview.simple import GetParaViewVersion

        return ".".join(str(part) for part in GetParaViewVersion())
    except Exception:  # noqa: BLE001 - not running under ParaView
        return "unknown"


def visit_attr(obj, name, default=None):
    """getattr() for a VisIt attribute object, where the builtin does not work.

    VisIt's attribute objects (ProcessAttributes, PlotList, and the rest)
    implement their own name lookup that raises ValueError -- not
    AttributeError -- for any name they do not carry. Two consequences, both
    measured on 3.4.2:

      * getattr(obj, "numProcs", 0) does NOT return 0. It raises
        ValueError("Could not find method with name `numProcs`"), so the
        default is never reached and the guard reads as safe while doing
        nothing. ex08 and ex10 both died this way.
      * dir(obj) raises too, because it asks for __class__ first. So the
        usual way of finding out what an object has does not work either;
        str(obj) prints the fields and is the way in.

    This returns `default` for anything that is not there, which is what the
    call sites believed they were already getting.
    """
    try:
        return getattr(obj, name)
    except Exception:  # noqa: BLE001 - ValueError today, anything tomorrow
        return default


VISIT_BUILTIN_TABLE_COUNT = 18


def visit_color_table_path(name):
    """Path to one of VisIt's own bundled .ct files, or None.

    VisIt installs ~129 colour tables under
    $VISITARCHHOME/resources/colortables/, and they are NOT the same set as
    the 18 compiled-in ones. `plasma`, `Blues` and `viridis` all live there.
    """
    arch = os.environ.get("VISITARCHHOME") or ""
    if not arch:
        return None
    path = os.path.join(arch, "resources", "colortables", name + ".ct")
    return path if os.path.exists(path) else None


def parse_visit_color_table(path):
    """[(colors, position), ...] from a VisIt .ct file. Stdlib only."""
    import xml.etree.ElementTree as ET

    points = []
    for obj in ET.parse(path).getroot().iter("Object"):
        if obj.get("name") != "ColorControlPointList":
            continue
        for child in obj:
            if child.get("name") != "ColorControlPoint":
                continue
            colors, position = None, None
            for field in child:
                if field.get("name") == "colors":
                    colors = tuple(int(v) for v in (field.text or "").split())
                elif field.get("name") == "position":
                    position = float(field.text)
            if colors and position is not None:
                points.append((colors, position))
    return points


def ensure_color_table(ctx, name, names_func, add_func, list_factory, point_factory):
    """Make `name` available, loading it from VisIt's install if need be.

    WHY THIS IS NEEDED

    The suite runs VisIt with -noconfig, so that a baseline is not partly a
    function of whose ~/.visit was on the machine that blessed it. That flag
    is blunter than it looks. Measured on 3.4.2:

        with    -noconfig :  18 colour tables
        without -noconfig : 157 colour tables

    Those 139 extra ones are not all the user's. Only 11 were; the other 129
    are VisIt's OWN, shipped as .ct files under
    $VISITARCHHOME/resources/colortables/ and loaded as part of the same
    config pass that -noconfig turns off. `viridis`, `plasma` and `Blues`
    are all VisIt's.

    So -noconfig alone would force the vignettes onto the 18 compiled-in
    tables, which is a real loss and not what was wanted: ex09 asks for
    viridis and ex06's session asks for plasma and Blues, and all three are
    perfectly portable -- they ship with VisIt and are the same on Shaheen
    and Ibex.

    Loading them explicitly from the install keeps both properties: the
    user's home directory stays out of the baselines, and VisIt's own tables
    stay in. A table that is already present is left alone.

    The VisIt callables are passed in so this module never imports visit.
    """
    available = set(names_func() or ())
    if name in available:
        ctx.debug("colour table already available: {0}".format(name))
        return name

    path = visit_color_table_path(name)
    if not path:
        raise VignetteError(
            "Colour table {0!r} is not available and no {0}.ct was found in "
            "this VisIt's resources directory ($VISITARCHHOME={1}). "
            "Available: {2}".format(
                name, os.environ.get("VISITARCHHOME"), ", ".join(sorted(available))
            )
        )

    points = parse_visit_color_table(path)
    if not points:
        raise VignetteError(
            "Colour table file {0} carried no control points".format(path)
        )

    table = list_factory()
    for colors, position in points:
        control = point_factory()
        control.colors = colors
        control.position = position
        table.AddControlPoints(control)
    add_func(name, table)
    ctx.log(
        "loaded colour table {0!r} from VisIt's install ({1} control "
        "points)".format(name, len(points))
    )
    return name


def ensure_flat_color_table(
    ctx, name, rgb, names_func, add_func, list_factory, point_factory
):
    """A colour table that is one colour at every position.

    VisIt's Pseudocolor plot takes its colour from a table, so there is no
    "just draw this plot in white". Where a plot needs to read as an
    annotation rather than as data -- ex09's isoline, which lies exactly on
    the surface it was cut from and would otherwise be painted the colour of
    whatever is directly behind it -- a two-point table with the same colour
    at both ends is how you say that.

    `rgb` is three floats in 0..1. Alpha is fixed opaque; a translucent
    annotation would make the frame depend on compositing order, which is
    rank-dependent (see ctx.disable_image_gate_off_baseline_ranks).

    Idempotent: a table already registered under `name` is left alone, so
    calling this once per topology costs nothing after the first.
    """
    if name in set(names_func() or ()):
        return name

    channels = [int(round(max(0.0, min(1.0, float(c))) * 255)) for c in rgb]
    table = list_factory()
    for position in (0.0, 1.0):
        control = point_factory()
        control.colors = (channels[0], channels[1], channels[2], 255)
        control.position = position
        table.AddControlPoints(control)
    add_func(name, table)
    ctx.log("built flat colour table {0!r} = rgb{1}".format(name, tuple(channels)))
    return name


def exit_vignette(code):
    """End a vignette process with `code`, skipping interpreter teardown.

    WHY THIS IS NOT sys.exit()
    --------------------------
    pvbatch 6.1.0 segfaults during Python finalization whenever a render
    window has been created and no usable X display exists -- which is every
    offscreen batch run and every Slurm compute node. Reduced to its
    essentials::

        cone = Cone(); v = GetActiveViewOrCreate("RenderView")
        Show(cone, v); SaveScreenshot(path, v)
        sys.exit(0)          # -> "error: exception occurred: Segmentation
                             #     fault", process exits 1

    The same script exits 0 when it falls off the end instead of calling
    sys.exit, and exits 0 under xvfb-run with a real display. The crash is
    therefore in teardown, after the vignette has finished and written
    everything, and it is not reachable from Python: deleting the view,
    ResetSession() and servermanager.Finalize() before exiting were all
    measured and none of them prevent it.

    That matters because the whole point of the reworked harness is that a
    vignette's exit code is a gate. A crash in teardown turns a clean pass
    into exit 1, so every rendering vignette failed on a correct run and the
    exit-code gate reported the opposite of the truth.

    os._exit() ends the process immediately with the requested status and
    never enters finalization, so the status is the vignette's own verdict
    and nothing else. Nothing is lost by skipping finalization here: the
    results JSON, the images and the extracts are all written and closed
    before this is reached. stdout and stderr are flushed explicitly,
    because os._exit does not flush them.

    VisIt vignettes do not use this. They shut down through
    finish_visit_session(), which must first close the compute engine --
    and therefore its Slurm allocation -- before the process can end.
    """
    try:
        sys.stdout.flush()
    except Exception:  # noqa: BLE001 - never mask the exit status
        pass
    try:
        sys.stderr.flush()
    except Exception:  # noqa: BLE001
        pass
    os._exit(int(code))


def _csv_cell(value):
    text = str(value)
    if any(ch in text for ch in (",", '"', "\n")):
        return '"' + text.replace('"', '""') + '"'
    return text


# ---------------------------------------------------------------------------
# VisIt compute-engine launch
# ---------------------------------------------------------------------------
def in_slurm_allocation():
    """True when this process is already inside a Slurm allocation.

    Set by Slurm for every job step, so it is true inside a job launched with
    sbatch and inside an salloc shell, and false on a login node.
    """
    return bool(os.environ.get("SLURM_JOB_ID") or os.environ.get("SLURM_JOBID"))


def _slurm_allocation_shape():
    """(nodes, tasks) of the current allocation, or (None, None)."""

    def _as_int(name):
        value = os.environ.get(name)
        try:
            return int(value)
        except (TypeError, ValueError):
            return None

    return _as_int("SLURM_NNODES") or _as_int("SLURM_JOB_NUM_NODES"), _as_int(
        "SLURM_NTASKS"
    )


def visit_engine_args(args, extra=None, inside_allocation=None):
    """Build OpenComputeEngine arguments, or None to stay in-process.

    Returns a tuple suitable for `OpenComputeEngine("localhost", <tuple>)`.
    `--machine local` never reaches a scheduler. At one rank it returns None
    and the vignette stays in-process; above one rank it returns `-np N`, so
    VisIt's bundled mpirun starts the engine locally. That makes a parallel
    rehearsal possible on a workstation before any queue time is spent.

    `extra` appends site-independent engine flags, such as -hw-accel to ask
    for a hardware-accelerated offscreen context on the engine.

    WHY THERE ARE TWO PROFILES
    --------------------------
    The site's VisIt customlauncher decides whether to take over by asking
    three questions at once::

        def IsRunningOnIbex(self):
            if self.parallelArgs.parallel and \
               self.sectorname().startswith("login") and \
               self.domainname() == "ibex.kaust.edu.sa":

    All three must hold, and the middle one is the decisive one here: the
    KAUST job submitters engage only when VisIt is started **on a login
    node**. That single condition splits every launch this repository makes
    into two cases that need different arguments.

    *Inside an allocation* -- which is where every .sbat script runs, because
    sbatch put us on a compute node -- the custom submitter does not engage.
    Asking for an sbatch launcher there would submit a second job from inside
    the first and wait for it to schedule. The engine must instead be started
    as a job **step** of the allocation we already hold, which is what
    ``-l srun`` does. Partition, account and walltime are deliberately
    omitted: a step inherits all three, and passing them turns into
    ``srun --partition=... --time=...``, which is redundant at best and
    rejected outright when it disagrees with the allocation.

    *On a login node* the custom submitter does engage, and it is an sbatch
    submitter with an srun sublauncher::

        def Executable(self):
            return ["sbatch"]
        ...
        sbatch, sublauncher = self.LauncherAndSubLauncher()
        if sublauncher == "srun":
            mpicmd = self.srun_args(args)

    ``LauncherAndSubLauncher()`` splits the launcher name on "/", so the
    launcher string has to be ``sbatch/srun`` for that branch to be taken --
    a bare ``-l srun`` would run the engine on the login node itself. Here
    partition, account and walltime are what the submitter turns into
    ``--partition=``, ``--account=`` and ``--time=`` on the sbatch line, so
    they are all passed. The account goes through ``-b``, VisIt's bank flag,
    because that is the field the submitter reads::

        if self.parallel.bank != None:
            parcmd = parcmd + ["--account=%s" % self.parallel.bank]

    `inside_allocation` overrides the detection, for testing.
    """
    nodes = max(1, int(args.nodes))
    ranks = max(1, int(args.ranks))

    if args.machine == "local":
        # A workstation has no scheduler, so a local run must not try to
        # reach one -- but `--ranks 1` and `--ranks 8` must not mean the same
        # thing either. Returning None for both is the trap this repository
        # already hit once at the other end (see the module header: the
        # walltime branch never matched, OpenComputeEngine was skipped, and
        # every Shaheen run executed serially on one rank while reporting the
        # rank count it had been asked for).
        #
        # `-np N` with no launcher uses VisIt's own bundled mpirun, which is
        # exactly what you want for rehearsing a parallel run locally before
        # spending queue time on it. One rank stays in-process, which is both
        # faster and what every committed baseline was blessed at.
        local = []
        if ranks > 1:
            local += ["-np", str(ranks)]
        if extra:
            local += list(extra)
        return tuple(local) if local else None

    if inside_allocation is None:
        inside_allocation = in_slurm_allocation()

    if inside_allocation:
        # A job step of the allocation we are already holding.
        launch = ["-l", "srun", "-nn", str(nodes), "-np", str(ranks)]
    else:
        # A fresh job, submitted through the site's customlauncher.
        launch = ["-l", "sbatch/srun", "-nn", str(nodes), "-np", str(ranks)]
        default_partition = "workq" if args.machine == "shaheen" else "batch"
        launch += ["-p", args.partition or default_partition]
        if getattr(args, "account", None):
            launch += ["-b", args.account]
        launch += ["-t", args.walltime]

    if extra:
        launch += list(extra)
    return tuple(launch)


def describe_visit_engine_launch(args, inside_allocation=None):
    """One line explaining which engine profile was chosen, and why.

    Written to the log because the two profiles fail in ways that look
    identical from the outside -- a hung OpenComputeEngine -- and knowing
    which one was attempted is most of the diagnosis.
    """
    if args.machine == "local":
        if max(1, int(args.ranks)) > 1:
            return (
                "machine=local with --ranks {0}: parallel engine through "
                "VisIt's bundled mpirun, nothing submitted".format(args.ranks)
            )
        return "machine=local: in-process engine, nothing submitted"

    if inside_allocation is None:
        inside_allocation = in_slurm_allocation()

    if not inside_allocation:
        return (
            "no Slurm allocation detected: submitting the engine with "
            "sbatch/srun, which is the launcher the site customlauncher "
            "expects from a login node"
        )

    job_id = os.environ.get("SLURM_JOB_ID") or os.environ.get("SLURM_JOBID")
    alloc_nodes, alloc_tasks = _slurm_allocation_shape()
    detail = "inside Slurm allocation {0}".format(job_id)
    if alloc_nodes or alloc_tasks:
        detail += " ({0} node(s), {1} task(s))".format(
            alloc_nodes if alloc_nodes is not None else "?",
            alloc_tasks if alloc_tasks is not None else "?",
        )
    return detail + ": starting the engine as a job step with srun"


def check_engine_fits_allocation(args):
    """Warnings for an engine request larger than the allocation holding it.

    srun rejects an oversubscribed step with a message about resources that
    reads like a queue problem rather than a configuration one, so the
    mismatch is worth naming before it happens. Returns a list of strings;
    an empty list means the request fits or there is nothing to compare to.
    """
    if not in_slurm_allocation():
        return []

    alloc_nodes, alloc_tasks = _slurm_allocation_shape()
    warnings = []
    if alloc_nodes is not None and int(args.nodes) > alloc_nodes:
        warnings.append(
            "--nodes {0} exceeds the {1} node(s) in this allocation; raise "
            "#SBATCH --nodes or lower VV_NODES".format(args.nodes, alloc_nodes)
        )
    if alloc_tasks is not None and int(args.ranks) > alloc_tasks:
        warnings.append(
            "--ranks {0} exceeds the {1} task(s) in this allocation; raise "
            "#SBATCH --ntasks-per-node or lower VV_RANKS".format(
                args.ranks, alloc_tasks
            )
        )
    return warnings


def finish_visit_session(ctx, code, close_compute_engine=None, exit_func=None):
    """Shut down a VisIt CLI script with a real process exit status.

    VisIt's CLI does not terminate when a script falls off the end, and a
    lingering client keeps the compute engine -- and therefore its Slurm
    allocation -- alive. Both shutdown paths are attempted and neither is
    allowed to mask the exit code:

      close_compute_engine  VisIt's CloseComputeEngine, passed in so this
                            module never imports the visit package.
      exit_func             VisIt's own exit(), which tears the viewer down
                            cleanly. Falls through to sys.exit if unavailable.
    """
    if close_compute_engine is not None:
        try:
            close_compute_engine()
        except Exception as exc:  # noqa: BLE001 - shutdown must not mask code
            ctx.warn("CloseComputeEngine failed: {0}".format(exc))

    if exit_func is not None:
        try:
            exit_func(code)
        except SystemExit:
            raise
        except Exception as exc:  # noqa: BLE001
            ctx.warn("VisIt exit() failed: {0}".format(exc))

    sys.exit(code)


def open_visit_engine(ctx, open_compute_engine, extra=None):
    """Launch a VisIt compute engine when the site calls for one.

    `open_compute_engine` is VisIt's OpenComputeEngine, passed in so this
    module never imports the visit package. Returns True when an engine was
    launched. `extra` forwards additional engine flags such as -hw-accel.
    """
    engine_args = visit_engine_args(ctx.args, extra=extra)
    if engine_args is None:
        ctx.log("machine=local at one rank: in-process, no compute engine")
        return False

    ctx.log(describe_visit_engine_launch(ctx.args))
    for warning in check_engine_fits_allocation(ctx.args):
        ctx.warn(warning)
    ctx.log("launching compute engine: {0}".format(" ".join(engine_args)))
    if not open_compute_engine("localhost", engine_args):
        raise VignetteError(
            "OpenComputeEngine failed for machine={0} nodes={1} ranks={2}".format(
                ctx.args.machine, ctx.args.nodes, ctx.args.ranks
            )
        )
    ctx.log("compute engine running")
    return True
