name: CI Pipeline

# This workflow runs on pushes to any branch and on pull requests.
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ############################################################################
  # BUILD JOB: Compiles the Docker image and pushes it to ghcr.io
  ############################################################################
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write # Required to push to GitHub Packages/ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: |
            # Create a tag for the branch name (e.g., my-feature)
            type=ref,event=branch
            # Create a tag for the git SHA
            type=sha,prefix=
            # Create the 'latest' tag only when pushing to the default branch (e.g., main)
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          # Don't push on pull requests, only build
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use local cache for self-hosted runners
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  ############################################################################
  # TEST JOB: Run ParaView tests
  ############################################################################
  paraview-test:
    name: ParaView Tests
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ParaView Test Suite
        shell: wsl -e bash {0}
        run: |
          echo "Running ParaView Tests"
          sudo apt-get update && sudo apt-get -y install wget make autoconf gfortran libmpich-dev python3-full python3-pip ffmpeg libsm6 libxext6 libgl1-mesa-glx
          python3 -V
          python3 -m venv test-venv
          source test-venv/bin/activate
          pip install pandas matplotlib psutil scipy
          wget -O paraview.tar.gz "https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.13&type=binary&os=Linux&downloadFile=ParaView-5.13.1-osmesa-MPI-Linux-Python3.10-x86_64.tar.gz"
          mkdir paraview
          tar xf paraview.tar.gz -C paraview --strip-components 1
          export PARAVIEW_DIR=$PWD/paraview/bin
          $PARAVIEW_DIR/pvbatch --version
          export PARAVIEW_PATH=$PARAVIEW_DIR
          REPO_DIR=$PWD
          cd Testing
          python3 test_suite.py $REPO_DIR/ --test_type ParaView --paraview_version 5.13.1 --non_gpu_machine
          echo "ParaView tests complete"

      - name: Upload ParaView Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: paraview-test-results
          path: |
            ParaView_Vignettes/*/Testing/*.json
            ParaView_Vignettes/*/Testing/*.log
            Testing/*.json
          retention-days: 30

  ############################################################################
  # TEST JOB: Run VisIt tests
  ############################################################################
  visit-test:
    name: VisIt Tests
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VisIt Test Suite
        shell: wsl -e bash {0}
        run: |
          echo "Running VisIt Tests"
          sudo apt-get update && sudo apt-get -y install wget make autoconf gfortran libmpich-dev python3-full python3-pip ffmpeg libsm6 libxext6 curl zip unzip libgl1-mesa-glx
          python3 -V
          python3 -m venv test-venv
          source test-venv/bin/activate
          pip install pandas matplotlib psutil scipy
          wget -O visit.tar.gz "https://github.com/visit-dav/visit/releases/download/v3.4.1/visit3_4_1.linux-x86_64-ubuntu22.tar.gz"
          mkdir visit
          tar xf visit.tar.gz -C visit --strip-components 1
          export VISIT_DIR=$PWD/visit/bin
          $VISIT_DIR/visit -version
          export VISIT_PATH=$VISIT_DIR
          REPO_DIR=$PWD
          cd Testing
          python3 test_suite.py $REPO_DIR/ --test_type VisIt --visit_version 3.4.1 --test_number 0 1 2 3 4 5
          echo "VisIt tests complete"

      - name: Upload VisIt Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visit-test-results
          path: |
            VisIt_Vignettes/*/Testing/*.json
            VisIt_Vignettes/*/Testing/*.log
            Testing/*.json
          retention-days: 30
